import {StyleSheet} from 'react-native';
import {COLORS, SIZES} from '../../constants';
import font from '../../assets/fonts/font';
const styles = StyleSheet.create({
  main: {},
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  upperRow: {
    // marginHorizontal: 20,
    marginLeft: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'absolute',
    top: SIZES.medium,
    zIndex: 999,
    width: SIZES.width - 24,
  },
  goToCartBtn: {
    padding: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderRadius: 14,
    elevation: 20,
  },
  galeryContainer: {
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  galeryItem: {
    height: 280,
  },
  img: {
    // aspectRatio: 1,
    resizeMode: 'contain',
    width: '100%',
    height: 300,
  },
  detail: {
    marginTop: 10,
    paddingBottom: 20,
    paddingHorizontal: SIZES.medium,
    // marginTop: -SIZES.large,
    backgroundColor: COLORS.white,
    width: SIZES.width,
    borderTopLeftRadius: SIZES.medium,
    borderTopRightRadius: SIZES.medium,
    elevation: 8,
    minHeight: SIZES.height - 290,
    overflow: 'hidden',
  },
  titleRow: {
    // marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: SIZES.width - 44,
    marginTop: 6,
  },
  title: {
    fontFamily: font.bold,
    fontSize: SIZES.large,
    color: '#000',
  },

  ratingRow: {
    // paddingBottom: SIZES.small,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rating: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ratingText: {
    color: COLORS.gray,
    fontFamily: font.medium,
  },
  packingOptionContainer: {
    width: 196,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  packingOptionBtn: onSelectedOption => ({
    marginBottom: 10,
    borderWidth: 1,
    elevation: onSelectedOption ? 4 : 0,
    backgroundColor: onSelectedOption ? COLORS.brown : '#fff',
    marginHorizontal: 2,
    // paddingHorizontal: 8,
    // paddingVertical: 4,
    borderColor: COLORS.brown,
    borderStyle: 'solid',
    borderRadius: 4,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: onSelectedOption ? 32 : 30,
    width: onSelectedOption ? 64 : 60,
  }),
  packingOptionText: onSelectedOption => ({
    color: onSelectedOption ? '#fff' : COLORS.brown,
    height: 24,
    width: '100%',
    textAlignVertical: 'center',
    textAlign: 'center',
  }),
  priceRow: {
    width: '100%',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  price: {
    height: '100%',
    fontFamily: font.semiBold,
    fontSize: 36,
    color: COLORS.red,
    height: 36,
    backgroundColor: '#ccc',
  },
  priceFlex: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceBefore: {
    fontFamily: font.regular,
    fontSize: SIZES.large,
    color: COLORS.gray,
    textDecorationLine: 'line-through',
    height: SIZES.xLarge,
  },
  priceAfter: {
    paddingHorizontal: 10,
    fontFamily: font.semiBold,
    fontSize: 36,
    color: COLORS.red,
    height: 36,
    marginBottom: 18,
  },
  counter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 0,
  },
  counterTitle: {
    marginRight: 20,
    fontFamily: font.semiBold,
    color: '#000',
  },
  counterText: {
    marginHorizontal: 6,
    color: '#000',
  },
  descWraper: {},
  desc: {
    fontFamily: font.bold,
    fontSize: SIZES.large,
    color: '#000',
  },
  descText: {
    fontFamily: font.regular,
    fontSize: SIZES.small,
    textAlign: 'justify',
    marginBottom: SIZES.small,
    color: '#000',
  },
  locationWrapper: {
    // marginTop: 10,
  },
  location: {
    left: -16,
    width: SIZES.width,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.primary,
    paddingHorizontal: 4,
    paddingVertical: 2,
    // borderRadius: SIZES.large,
    // marginHorizontal: 12,
  },
  locationRow: {
    flexDirection: 'row',
  },
  locationTxt: {
    marginLeft: 2,
    color: '#000',
  },
  deliveryTxt: {
    marginLeft: 8,
    color: '#000',
    marginRight: 8,
  },
  cartRow: {
    paddingBottom: SIZES.small,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  cartBtn: {
    // width: SIZES.width * 0.6,
    backgroundColor: '#000',
    padding: SIZES.small / 2,
    borderRadius: SIZES.large,
    paddingHorizontal: 20,
  },
  cartTitle: {
    fontFamily: font.semiBold,
    fontSize: SIZES.medium,
    color: COLORS.lightWhite,
    // marginLeft: 24,
    marginTop: 4,
  },
  addCart: {
    width: 44,
    height: 44,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  relatedWraper: {
    width: SIZES.width - 10,
    left: -10,
  },
  relatedTitle: {
    marginLeft: 10,
    fontFamily: font.bold,
    fontSize: SIZES.large,
    color: '#000',
  },
});
export default styles;
